### ISSUE TITLE
编辑器的配置文件都传上来了鸭

### ISSUE THREAD

**Issue by adoontheway** [fananchong/go-xserver#2]
RT

**Comment by fananchong** [comment]
你说的编辑器是指 vscode 吗？

**Comment by adoontheway** [comment]
还有editorconfig文件

**Comment by fananchong** [comment]
go 代码可以用 vscode 作为编辑器
vscode 的环境搭建，可以参考： https://blog.csdn.net/u013272009/article/details/84971807
